server:
  port: 8080

spring:
  profiles:
    active: local
  ai:
    dashscope:
      api-key: placeholder

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.aichat: DEBUG
    com.alibaba.cloud.ai: DEBUG

jwt:
  expiration: 86400000
